### ISSUE TITLE
BXML Callback Events

### ISSUE THREAD

**Issue by rdennis** [Bandwidth/csharp-bandwidth#73]
I'm having trouble using `CallbackEvent.CreateFromJson` when the `EventType` is a BXML Callback Event (specifically `transferComplete`). I see that the `EventType` enum doesn't contain these events. I'm wondering, is this just an oversight, or is `CallbackEvent.CreateFromJson` not meant to be used for BXML Callbacks?

**Comment by avbel** [comment]
Fixed in `3.0.13`. Update the lib please.

**Comment by rdennis** [comment]
Ok, thanks. I see that the `redirect` `EventType` isn't in the enum either.

Also, what is the time table for updating the nuget package? I prefer to use nuget instead of local assemblies as much as possible.

**Comment by avbel** [comment]
5-15 minutes after pushing to master and creating a tag. New version is in
nuget already

ср, 28 мар. 2018 г., 17:37 rdennis <notifications@github.com>:

**Comment by rdennis** [comment]
Ah, I see it now. I was expecting the tag to be `3.1.x`, not `3.0.13`. Thanks.
