### ISSUE TITLE
List() method gets stuck and hanged

### ISSUE THREAD

**Issue by philiplin1208** [Bandwidth/csharp-bandwidth#76]
Hi there, 

I am trying Bandwidth in my application. But when I tried to retrieve past SMS messages using the code: 
`var msgList = Client.Message.List();`
`var list = msgList.ToList();`
I can't retrieve the messages. The program just gets stuck and nothing returns, not even an exception. My application is using .NET 4.5.2 and I am using a trial account of Bandwidth. 
As I inspect the code for Message.List(), 

`return new LazyEnumerable<Message>(Client, 
() => 
Client.MakeJsonRequestAsync(HttpMethod.Get, $"/users/{Client.UserId}/messages", cancellationToken, query));`

I think the possible cause could be that my framework does not support the LazyEnumerable collection. 
(And I could not find any information on the collection)

Please help...Thanks!

Philip Lin

**Comment by avbel** [comment]
I couldn't reproduce this issues. Next demo (console app) works fine for me.
```csharp
  class Program
  {
    static void Main()
    {
      var client = new Client("u-xxxxxxx", "t-yyyyyyy", "zzzzzzzzzzzzzzzzzzz");
      var messages = client.Message.List().ToList();
      Console.WriteLine("Total {0} messages", messages.Count);
    }
  }
```

I think I know the reason of "stuck". Do you call `client.Message.List().ToList();` in UI thread? If yes this is a reason of you issue.

**Comment by avbel** [comment]
Shortly main rule of UI development: never do long time operations or operations with locks in ui thread.  All (may be almost) UIs are singlethreaded. Any long operations in ui thread can be reason of "freezes" in ui. 
Modern UI libs has own tools to "synchronize" (refresh) UI from another threads. For example show data whci were loaded in another thread.
Feature of .Net UI libs (at least for Windows): it makes all called from ui thread async operations to be executed in same ui thread (for example to save ability to get access to ui elements).

About "stuck" in your case `client.Message.List()` makes async operation to load data and waits result. You called this function inside UI thread which makes alls async operations to be executed in same thread (i.e. in UI thread). As result waiting of results locks UI thread forever. It is not bug of this lib. It is feauture of UI thread (at least on Windows). 

When you run `client.Message.List()` in non-ui thread async operation is executed in another thread (from thread pool). Current thread is locked for results. After receving results current thread is restored.
