### ISSUE TITLE
Can't tag issues

### ISSUE THREAD

**Issue by breyed** [Bandwidth/csharp-bandwidth#78]
The readme's Providing Feedback section asks users to tag new issues:

> For current discussions on 3.0 please see the 3.0 issues section on GitHub. To start a new topic on 3.0, please open an issue and use the 3.0 tag. Your feedback is greatly appreciated!

However, regular users can't tag issues in GitHub. Only project members can.

I would have tagged this issue as being related to version 3.0, except, well, I can't. :-)

**Comment by dtolb** [comment]
Oh! well, that's news to me. I've added that label to ya. I'll also go through and remove that lil section of the Readme
