### ISSUE TITLE
Bandwidth.Net.Api.CallQuery Class is missing page property

### ISSUE THREAD

**Issue by charlieneo** [Bandwidth/csharp-bandwidth#79]
According to https://dev.bandwidth.com/ap-docs/methods/calls/getCalls.html

page and size is needed for full pagination capability.

**Comment by avbel** [comment]
It is not error. Method `List()` will return you all calls(domain, numbers, etc) on demand. It uses lazy-computation. So you can stop it when you need. For example `client.Call.List().Take(100)` will return first 100 calls (additional requests to Bandwidth server will be made on demand).
The code `client.Call.List().Skip(100).Take(100)` will return you next 100 calls.

To decrease numbers requests to Bandwidth server you can use parameter `Size`. For example

```csharp
// only 1 request to Bandwidth server will be executed
client.Call.List(new CallQuery{Size = 200}).Skip(100).Take(100);
```
