### ISSUE TITLE
Downloading Media in ApiV2

### ISSUE THREAD

**Issue by maxmaceachern** [Bandwidth/csharp-bandwidth#88]
In the ApiV1 we previously had access to Media.DownloadAsync that we used to download media files uploaded to the Bandwidth servers. We are migrating to Bandwidth V2 and don't see an associated method in ApiV2. Is that indeed the case? If so, I assume we need to getMedia call outlined in the V2 Messaging documentation and parse the response ourselves? Further, are there plans to expose this functionality to ApiV2?

**Comment by dtolb** [comment]
@maxmaceachern thanks for reaching out! Right now we're in the process of updating everything to be more v2-focused.  Look for an update sometime this Fall for a more complete v2-experience. 

As always, we're happy to review a pull-request implementing the updated media fetch method.
